//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBaseBall.ServicioEquipos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioEquipos.ISrvEquipos")]
    public interface ISrvEquipos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvEquipos/GetAñoInicial", ReplyAction="http://tempuri.org/ISrvEquipos/GetAñoInicialResponse")]
        int GetAñoInicial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvEquipos/GetAñoInicial", ReplyAction="http://tempuri.org/ISrvEquipos/GetAñoInicialResponse")]
        System.Threading.Tasks.Task<int> GetAñoInicialAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvEquipos/GetAñoFinal", ReplyAction="http://tempuri.org/ISrvEquipos/GetAñoFinalResponse")]
        int GetAñoFinal();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvEquipos/GetAñoFinal", ReplyAction="http://tempuri.org/ISrvEquipos/GetAñoFinalResponse")]
        System.Threading.Tasks.Task<int> GetAñoFinalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvEquipos/GetEquiposByYear", ReplyAction="http://tempuri.org/ISrvEquipos/GetEquiposByYearResponse")]
        BaseBall.Modelos.Equipo[] GetEquiposByYear(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvEquipos/GetEquiposByYear", ReplyAction="http://tempuri.org/ISrvEquipos/GetEquiposByYearResponse")]
        System.Threading.Tasks.Task<BaseBall.Modelos.Equipo[]> GetEquiposByYearAsync(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvEquipos/GetJugadoresEquipoAño", ReplyAction="http://tempuri.org/ISrvEquipos/GetJugadoresEquipoAñoResponse")]
        BaseBall.Modelos.Player[] GetJugadoresEquipoAño(string idTeam, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvEquipos/GetJugadoresEquipoAño", ReplyAction="http://tempuri.org/ISrvEquipos/GetJugadoresEquipoAñoResponse")]
        System.Threading.Tasks.Task<BaseBall.Modelos.Player[]> GetJugadoresEquipoAñoAsync(string idTeam, int year);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISrvEquiposChannel : MvcBaseBall.ServicioEquipos.ISrvEquipos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SrvEquiposClient : System.ServiceModel.ClientBase<MvcBaseBall.ServicioEquipos.ISrvEquipos>, MvcBaseBall.ServicioEquipos.ISrvEquipos {
        
        public SrvEquiposClient() {
        }
        
        public SrvEquiposClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SrvEquiposClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvEquiposClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvEquiposClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetAñoInicial() {
            return base.Channel.GetAñoInicial();
        }
        
        public System.Threading.Tasks.Task<int> GetAñoInicialAsync() {
            return base.Channel.GetAñoInicialAsync();
        }
        
        public int GetAñoFinal() {
            return base.Channel.GetAñoFinal();
        }
        
        public System.Threading.Tasks.Task<int> GetAñoFinalAsync() {
            return base.Channel.GetAñoFinalAsync();
        }
        
        public BaseBall.Modelos.Equipo[] GetEquiposByYear(int year) {
            return base.Channel.GetEquiposByYear(year);
        }
        
        public System.Threading.Tasks.Task<BaseBall.Modelos.Equipo[]> GetEquiposByYearAsync(int year) {
            return base.Channel.GetEquiposByYearAsync(year);
        }
        
        public BaseBall.Modelos.Player[] GetJugadoresEquipoAño(string idTeam, int year) {
            return base.Channel.GetJugadoresEquipoAño(idTeam, year);
        }
        
        public System.Threading.Tasks.Task<BaseBall.Modelos.Player[]> GetJugadoresEquipoAñoAsync(string idTeam, int year) {
            return base.Channel.GetJugadoresEquipoAñoAsync(idTeam, year);
        }
    }
}
